### ISSUE TITLE
Tilføj test som `qa` skulle dække

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#820]
- [x] test af at post/get/websocket kald til transformere virker #867 
- [x] gennemgå transformer-test-cases (automatisk genererede tests for de cases der er i apitest) #865
- [x] sikr at swagger-validering virker
- [x] fjern `qa`-mappen #868

**Comment by KiraH** [comment]
lukker denne
